### ISSUE TITLE
actual,expected checksum wrongly displaying

### ISSUE THREAD

**Issue by ghost** [mariokonrad/marnav#19] opened 2018-10-01 05:31 UTC
In ensure_checksum() of nmea.cpp we are calculating checksum and considering it as actual checksum. we are providing wrong information here, calculated checksum must be the expected checksum and actual checksum is the one we received from the message. in case if we pass a wrong checksum(34) and actual checksum is (44) we will be getting below message

**checksum error: (actual:44, expected:34)**

but it must be printed as

**checksum error:(actual: 34, expected:44)**

**Comment by mariokonrad** [comment] 2018-10-01 18:59
The function works as intended. If you expect (expectation of the user for the function) a checksum of '34', but the actual (computed from the specified sentence) one is '44', this is exactly as it the checksum error says (actual:44, expected:34).

**Comment by mariokonrad** [comment] 2018-10-09 20:02
I think this is going nowhere. Closing.

**Closed by mariokonrad** 2018-10-09 20:02 UTC
