### ISSUE TITLE
AIS broadcast message text corruption

### ISSUE THREAD

**Issue by ShadowTeolog** [mariokonrad/marnav#7] opened 2017-09-05 09:56 UTC
message text for this kind of message corrupting while encoding.
this code will result AIS SART ??????? string. decoding by over ais library do same result so reason in encoding part.
Compiler: Visual Studio 2015 x86
        
const char AisSartMessage[] = "AIS SART activated";
	using namespace marnav;
	ais::message_14 broadcast;
	broadcast.set_mmsi(utils::mmsi(cs));
	broadcast.set_repeat_indicator(IsRepeat);
	broadcast.set_text(AisSartMessage);
	auto payload = encode_message(broadcast);
	{
		auto message = ais::make_message(payload);
		if (message->type() == ais::message_id::safety_related_broadcast_message) {
			auto report = ais::message_cast<ais::message_14>(message);
			auto messagetext = report->get_text();
                          assert(messagetext==AisSartMessage);
		}
	}

**Comment by mariokonrad** [comment] 2017-09-05 11:55
Thanks, I'll look into it this week.

**Comment by ShadowTeolog** [comment] 2017-09-05 13:41
Not need, I'am found it. This result of lowercase letters ;)
std::to_upper helps to fix this.

**Comment by derrix060** [comment] 2017-11-09 22:00
close?

**Comment by mariokonrad** [comment] 2017-11-11 13:10
Sorry, unfortunately I had no time to look into it.
If it is an issue about lower- vs. uppercase letters, the library could (a) ensure the proper case or (b) document requirements of the interface. The problem is, I have no specification and am dependent on information from other people or websites, but it has to be not derived from the specification...

**Comment by mariokonrad** [comment] 2017-11-27 22:51
It probably makes sense to close this issue.

**Closed by mariokonrad** 2017-11-27 22:51 UTC
